### ISSUE TITLE
[Umbrella][Endpoints]

### ISSUE THREAD

**Issue by ifilonenko** [cuappdev/podcast-ml#11]
This git issue tracks current progress on podcast-ml in relation to the main podcast-backend which will be issuing requests to this microserver for all discovery-ml features. 

- [ ] Recommend episodes per User 
- [ ] Recommend series per User
- [ ] Top 10 Series per Topic
- [ ] Top 10 Episodes per Topic
