### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by kevingreer** [cuappdev/podcast-ml#15]
- [ ] Make podcast-backend endpoints that connect to our podcast-ml Flask app
- [ ] Set up topic endpoints by reading from iTunes RSS feeds
- [ ] Writing score tuples to Redis before training
- [ ] Dockerizing the training pyspark job
- [ ] ALS training and generating predictions, then writing the predictions to MySQL db
