### ISSUE TITLE
[Cache Layer][Umbrella Issue]

### ISSUE THREAD

**Issue by ifilonenko** [cuappdev/podcast-ml#9]
This issue is tracking all work being done on creating a cache layer that stores the TFIDF representation of podcast descriptions and metadata. These are Matrices and will be stored on a Redis cluster.

- [ ] Setup connector that pushes and pulls to Redis via Python
- [ ] Design methods that leverage the connector to push and pull Matricies
- [ ] Handle ingestion of podcast data and store in Redis as TFIDF 
- [ ] Handle pulling of podcast data with necessary metadata
- [ ] Handle pushing and pulling Neural Net weights to Redis for caching trained models
